// Code generated by svdxgen; DO NOT EDIT.

//go:build rp2350

// Package hstxfifo provides access to the registers of the HSTX_FIFO peripheral.
//
// Instances:
//
//	HSTX_FIFO  HSTX_FIFO_BASE  -  -  FIFO status and write access for HSTX
//
// Registers:
//
//	0x000 32  STAT  FIFO status
//	0x004 32  FIFO  Write access to FIFO
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package hstxfifo

const (
	LEVEL STAT = 0xFF << 0  //+
	FULL  STAT = 0x01 << 8  //+
	EMPTY STAT = 0x01 << 9  //+
	WOF   STAT = 0x01 << 10 //+ FIFO was written when full. Write 1 to clear.
)

const (
	LEVELn = 0
	FULLn  = 8
	EMPTYn = 9
	WOFn   = 10
)
