// Code generated by svdxgen; DO NOT EDIT.

//go:build rp2350

// Package psm provides access to the registers of the PSM peripheral.
//
// Instances:
//
//	PSM  PSM_BASE  -  -
//
// Registers:
//
//	0x000 32  FRCE_ON   Force block out of reset (i.e. power it on)
//	0x004 32  FRCE_OFF  Force into reset (i.e. power it off)
//	0x008 32  WDSEL     Set to 1 if the watchdog should reset this
//	0x00C 32  DONE      Is the subsystem ready?
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package psm

const (
	PROC_COLD  FRCE_ON = 0x01 << 0  //+
	OTP        FRCE_ON = 0x01 << 1  //+
	ROSC       FRCE_ON = 0x01 << 2  //+
	XOSC       FRCE_ON = 0x01 << 3  //+
	RESETS     FRCE_ON = 0x01 << 4  //+
	CLOCKS     FRCE_ON = 0x01 << 5  //+
	PSM_READY  FRCE_ON = 0x01 << 6  //+
	BUSFABRIC  FRCE_ON = 0x01 << 7  //+
	ROM        FRCE_ON = 0x01 << 8  //+
	BOOTRAM    FRCE_ON = 0x01 << 9  //+
	SRAM0      FRCE_ON = 0x01 << 10 //+
	SRAM1      FRCE_ON = 0x01 << 11 //+
	SRAM2      FRCE_ON = 0x01 << 12 //+
	SRAM3      FRCE_ON = 0x01 << 13 //+
	SRAM4      FRCE_ON = 0x01 << 14 //+
	SRAM5      FRCE_ON = 0x01 << 15 //+
	SRAM6      FRCE_ON = 0x01 << 16 //+
	SRAM7      FRCE_ON = 0x01 << 17 //+
	SRAM8      FRCE_ON = 0x01 << 18 //+
	SRAM9      FRCE_ON = 0x01 << 19 //+
	XIP        FRCE_ON = 0x01 << 20 //+
	SIO        FRCE_ON = 0x01 << 21 //+
	ACCESSCTRL FRCE_ON = 0x01 << 22 //+
	PROC0      FRCE_ON = 0x01 << 23 //+
	PROC1      FRCE_ON = 0x01 << 24 //+
)

const (
	PROC_COLDn  = 0
	OTPn        = 1
	ROSCn       = 2
	XOSCn       = 3
	RESETSn     = 4
	CLOCKSn     = 5
	PSM_READYn  = 6
	BUSFABRICn  = 7
	ROMn        = 8
	BOOTRAMn    = 9
	SRAM0n      = 10
	SRAM1n      = 11
	SRAM2n      = 12
	SRAM3n      = 13
	SRAM4n      = 14
	SRAM5n      = 15
	SRAM6n      = 16
	SRAM7n      = 17
	SRAM8n      = 18
	SRAM9n      = 19
	XIPn        = 20
	SIOn        = 21
	ACCESSCTRLn = 22
	PROC0n      = 23
	PROC1n      = 24
)

const (
	PROC_COLD  FRCE_OFF = 0x01 << 0  //+
	OTP        FRCE_OFF = 0x01 << 1  //+
	ROSC       FRCE_OFF = 0x01 << 2  //+
	XOSC       FRCE_OFF = 0x01 << 3  //+
	RESETS     FRCE_OFF = 0x01 << 4  //+
	CLOCKS     FRCE_OFF = 0x01 << 5  //+
	PSM_READY  FRCE_OFF = 0x01 << 6  //+
	BUSFABRIC  FRCE_OFF = 0x01 << 7  //+
	ROM        FRCE_OFF = 0x01 << 8  //+
	BOOTRAM    FRCE_OFF = 0x01 << 9  //+
	SRAM0      FRCE_OFF = 0x01 << 10 //+
	SRAM1      FRCE_OFF = 0x01 << 11 //+
	SRAM2      FRCE_OFF = 0x01 << 12 //+
	SRAM3      FRCE_OFF = 0x01 << 13 //+
	SRAM4      FRCE_OFF = 0x01 << 14 //+
	SRAM5      FRCE_OFF = 0x01 << 15 //+
	SRAM6      FRCE_OFF = 0x01 << 16 //+
	SRAM7      FRCE_OFF = 0x01 << 17 //+
	SRAM8      FRCE_OFF = 0x01 << 18 //+
	SRAM9      FRCE_OFF = 0x01 << 19 //+
	XIP        FRCE_OFF = 0x01 << 20 //+
	SIO        FRCE_OFF = 0x01 << 21 //+
	ACCESSCTRL FRCE_OFF = 0x01 << 22 //+
	PROC0      FRCE_OFF = 0x01 << 23 //+
	PROC1      FRCE_OFF = 0x01 << 24 //+
)

const (
	PROC_COLDn  = 0
	OTPn        = 1
	ROSCn       = 2
	XOSCn       = 3
	RESETSn     = 4
	CLOCKSn     = 5
	PSM_READYn  = 6
	BUSFABRICn  = 7
	ROMn        = 8
	BOOTRAMn    = 9
	SRAM0n      = 10
	SRAM1n      = 11
	SRAM2n      = 12
	SRAM3n      = 13
	SRAM4n      = 14
	SRAM5n      = 15
	SRAM6n      = 16
	SRAM7n      = 17
	SRAM8n      = 18
	SRAM9n      = 19
	XIPn        = 20
	SIOn        = 21
	ACCESSCTRLn = 22
	PROC0n      = 23
	PROC1n      = 24
)

const (
	PROC_COLD  WDSEL = 0x01 << 0  //+
	OTP        WDSEL = 0x01 << 1  //+
	ROSC       WDSEL = 0x01 << 2  //+
	XOSC       WDSEL = 0x01 << 3  //+
	RESETS     WDSEL = 0x01 << 4  //+
	CLOCKS     WDSEL = 0x01 << 5  //+
	PSM_READY  WDSEL = 0x01 << 6  //+
	BUSFABRIC  WDSEL = 0x01 << 7  //+
	ROM        WDSEL = 0x01 << 8  //+
	BOOTRAM    WDSEL = 0x01 << 9  //+
	SRAM0      WDSEL = 0x01 << 10 //+
	SRAM1      WDSEL = 0x01 << 11 //+
	SRAM2      WDSEL = 0x01 << 12 //+
	SRAM3      WDSEL = 0x01 << 13 //+
	SRAM4      WDSEL = 0x01 << 14 //+
	SRAM5      WDSEL = 0x01 << 15 //+
	SRAM6      WDSEL = 0x01 << 16 //+
	SRAM7      WDSEL = 0x01 << 17 //+
	SRAM8      WDSEL = 0x01 << 18 //+
	SRAM9      WDSEL = 0x01 << 19 //+
	XIP        WDSEL = 0x01 << 20 //+
	SIO        WDSEL = 0x01 << 21 //+
	ACCESSCTRL WDSEL = 0x01 << 22 //+
	PROC0      WDSEL = 0x01 << 23 //+
	PROC1      WDSEL = 0x01 << 24 //+
)

const (
	PROC_COLDn  = 0
	OTPn        = 1
	ROSCn       = 2
	XOSCn       = 3
	RESETSn     = 4
	CLOCKSn     = 5
	PSM_READYn  = 6
	BUSFABRICn  = 7
	ROMn        = 8
	BOOTRAMn    = 9
	SRAM0n      = 10
	SRAM1n      = 11
	SRAM2n      = 12
	SRAM3n      = 13
	SRAM4n      = 14
	SRAM5n      = 15
	SRAM6n      = 16
	SRAM7n      = 17
	SRAM8n      = 18
	SRAM9n      = 19
	XIPn        = 20
	SIOn        = 21
	ACCESSCTRLn = 22
	PROC0n      = 23
	PROC1n      = 24
)

const (
	PROC_COLD  DONE = 0x01 << 0  //+
	OTP        DONE = 0x01 << 1  //+
	ROSC       DONE = 0x01 << 2  //+
	XOSC       DONE = 0x01 << 3  //+
	RESETS     DONE = 0x01 << 4  //+
	CLOCKS     DONE = 0x01 << 5  //+
	PSM_READY  DONE = 0x01 << 6  //+
	BUSFABRIC  DONE = 0x01 << 7  //+
	ROM        DONE = 0x01 << 8  //+
	BOOTRAM    DONE = 0x01 << 9  //+
	SRAM0      DONE = 0x01 << 10 //+
	SRAM1      DONE = 0x01 << 11 //+
	SRAM2      DONE = 0x01 << 12 //+
	SRAM3      DONE = 0x01 << 13 //+
	SRAM4      DONE = 0x01 << 14 //+
	SRAM5      DONE = 0x01 << 15 //+
	SRAM6      DONE = 0x01 << 16 //+
	SRAM7      DONE = 0x01 << 17 //+
	SRAM8      DONE = 0x01 << 18 //+
	SRAM9      DONE = 0x01 << 19 //+
	XIP        DONE = 0x01 << 20 //+
	SIO        DONE = 0x01 << 21 //+
	ACCESSCTRL DONE = 0x01 << 22 //+
	PROC0      DONE = 0x01 << 23 //+
	PROC1      DONE = 0x01 << 24 //+
)

const (
	PROC_COLDn  = 0
	OTPn        = 1
	ROSCn       = 2
	XOSCn       = 3
	RESETSn     = 4
	CLOCKSn     = 5
	PSM_READYn  = 6
	BUSFABRICn  = 7
	ROMn        = 8
	BOOTRAMn    = 9
	SRAM0n      = 10
	SRAM1n      = 11
	SRAM2n      = 12
	SRAM3n      = 13
	SRAM4n      = 14
	SRAM5n      = 15
	SRAM6n      = 16
	SRAM7n      = 17
	SRAM8n      = 18
	SRAM9n      = 19
	XIPn        = 20
	SIOn        = 21
	ACCESSCTRLn = 22
	PROC0n      = 23
	PROC1n      = 24
)
