// Code generated by svdxgen; DO NOT EDIT.

//go:build rp2350

// Package tbman provides access to the registers of the TBMAN peripheral.
//
// Instances:
//
//	TBMAN  TBMAN_BASE  -  -  For managing simulation testbenches
//
// Registers:
//
//	0x000 32  PLATFORM  Indicates the type of platform in use
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package tbman

const (
	ASIC   PLATFORM = 0x01 << 0 //+ Indicates the platform is an ASIC
	FPGA   PLATFORM = 0x01 << 1 //+ Indicates the platform is an FPGA
	HDLSIM PLATFORM = 0x01 << 2 //+ Indicates the platform is a simulation
)

const (
	ASICn   = 0
	FPGAn   = 1
	HDLSIMn = 2
)
