// Code generated by svdxgen; DO NOT EDIT.

//go:build rp2350

// Package ticks provides access to the registers of the TICKS peripheral.
//
// Instances:
//
//	TICKS  TICKS_BASE  -  -
//
// Registers:
//
//	0x000 32  T{CTRL,CYCLES,COUNT}[6]  Controls the tick generator
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package ticks

const (
	PROC0    int = 0x00 << 0 //+ Index to the PROC0 register in the T array
	PROC1    int = 0x01 << 0 //+ Index to the PROC1 register in the T array
	TIMER0   int = 0x02 << 0 //+ Index to the TIMER0 register in the T array
	TIMER1   int = 0x03 << 0 //+ Index to the TIMER1 register in the T array
	WATCHDOG int = 0x04 << 0 //+ Index to the WATCHDOG register in the T array
	RISCV    int = 0x05 << 0 //+ Index to the RISCV register in the T array
)

const (
	ENABLE  CTRL = 0x01 << 0 //+ start / stop tick generation
	RUNNING CTRL = 0x01 << 1 //+ Is the tick generator running?
)

const (
	ENABLEn  = 0
	RUNNINGn = 1
)
