// Code generated by svdxgen; DO NOT EDIT.

//go:build rp2350

// Package sysinfo provides access to the registers of the SYSINFO peripheral.
//
// Instances:
//
//	SYSINFO  SYSINFO_BASE  -  -
//
// Registers:
//
//	0x000 32  CHIP_ID        JEDEC JEP-106 compliant chip identifier.
//	0x004 32  PACKAGE_SEL
//	0x008 32  PLATFORM       Platform register. Allows software to know what environment it is running in during pre-production development. Post-production, the PLATFORM is always ASIC, non-SIM.
//	0x014 32  GITREF_RP2350  Git hash of the chip source. Used to identify chip version.
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package sysinfo

const (
	STOP_BIT     CHIP_ID = 0x01 << 0    //+
	MANUFACTURER CHIP_ID = 0x7FF << 1   //+
	PART         CHIP_ID = 0xFFFF << 12 //+
	REVISION     CHIP_ID = 0x0F << 28   //+
)

const (
	STOP_BITn     = 0
	MANUFACTURERn = 1
	PARTn         = 12
	REVISIONn     = 28
)

const (
	FPGA     PLATFORM = 0x01 << 0 //+
	ASIC     PLATFORM = 0x01 << 1 //+
	HDLSIM   PLATFORM = 0x01 << 2 //+
	BATCHSIM PLATFORM = 0x01 << 3 //+
	GATESIM  PLATFORM = 0x01 << 4 //+
)

const (
	FPGAn     = 0
	ASICn     = 1
	HDLSIMn   = 2
	BATCHSIMn = 3
	GATESIMn  = 4
)
