// Code generated by svdxgen; DO NOT EDIT.

//go:build rp2350

// Package resets provides access to the registers of the RESETS peripheral.
//
// Instances:
//
//	RESETS  RESETS_BASE  -  -
//
// Registers:
//
//	0x000 32  RESET(uint32)
//	0x004 32  WDSEL(uint32)
//	0x008 32  RESET_DONE(uint32)
//
// Import:
//
//	github.com/embeddedgo/pico/p/mmap
package resets

const (
	ADC        uint32 = 0x01 << 0  //+
	BUSCTRL    uint32 = 0x01 << 1  //+
	DMA        uint32 = 0x01 << 2  //+
	HSTX       uint32 = 0x01 << 3  //+
	I2C0       uint32 = 0x01 << 4  //+
	I2C1       uint32 = 0x01 << 5  //+
	IO_BANK0   uint32 = 0x01 << 6  //+
	IO_QSPI    uint32 = 0x01 << 7  //+
	JTAG       uint32 = 0x01 << 8  //+
	PADS_BANK0 uint32 = 0x01 << 9  //+
	PADS_QSPI  uint32 = 0x01 << 10 //+
	PIO0       uint32 = 0x01 << 11 //+
	PIO1       uint32 = 0x01 << 12 //+
	PIO2       uint32 = 0x01 << 13 //+
	PLL_SYS    uint32 = 0x01 << 14 //+
	PLL_USB    uint32 = 0x01 << 15 //+
	PWM        uint32 = 0x01 << 16 //+
	SHA256     uint32 = 0x01 << 17 //+
	SPI0       uint32 = 0x01 << 18 //+
	SPI1       uint32 = 0x01 << 19 //+
	SYSCFG     uint32 = 0x01 << 20 //+
	SYSINFO    uint32 = 0x01 << 21 //+
	TBMAN      uint32 = 0x01 << 22 //+
	TIMER0     uint32 = 0x01 << 23 //+
	TIMER1     uint32 = 0x01 << 24 //+
	TRNG       uint32 = 0x01 << 25 //+
	UART0      uint32 = 0x01 << 26 //+
	UART1      uint32 = 0x01 << 27 //+
	USBCTRL    uint32 = 0x01 << 28 //+
)

const (
	ADCn        = 0
	BUSCTRLn    = 1
	DMAn        = 2
	HSTXn       = 3
	I2C0n       = 4
	I2C1n       = 5
	IO_BANK0n   = 6
	IO_QSPIn    = 7
	JTAGn       = 8
	PADS_BANK0n = 9
	PADS_QSPIn  = 10
	PIO0n       = 11
	PIO1n       = 12
	PIO2n       = 13
	PLL_SYSn    = 14
	PLL_USBn    = 15
	PWMn        = 16
	SHA256n     = 17
	SPI0n       = 18
	SPI1n       = 19
	SYSCFGn     = 20
	SYSINFOn    = 21
	TBMANn      = 22
	TIMER0n     = 23
	TIMER1n     = 24
	TRNGn       = 25
	UART0n      = 26
	UART1n      = 27
	USBCTRLn    = 28
)
