// Code generated by xgen -g; DO NOT EDIT.

//go:build rp2350

package resets

import (
	"embedded/mmio"
	"structs"
	"unsafe"

	"github.com/embeddedgo/pico/p/mmap"
)

type Periph struct {
	_ structs.HostLayout

	RESET      mmio.R32[uint32]
	WDSEL      mmio.R32[uint32]
	RESET_DONE mmio.R32[uint32]
}

func RESETS() *Periph { return (*Periph)(unsafe.Pointer(uintptr(mmap.RESETS_BASE))) }

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}
